#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherApplication.Resource", IsApplication=true)]

namespace WeatherApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int celsius = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int cityInput = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int countryCodeRes = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int countryCodeTxt = 2130968590;
			
			// aapt resource value: 0x7f040007
			public const int defaultTxtGrid = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int defaultValuesGrid = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int descriptionRes = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int descriptionTxt = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int fahrenheit = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int inputGrid = 2130968576;
			
			// aapt resource value: 0x7f04001d
			public const int optCoordinates = 2130968605;
			
			// aapt resource value: 0x7f040019
			public const int optHumidity = 2130968601;
			
			// aapt resource value: 0x7f040017
			public const int optMaxTemp = 2130968599;
			
			// aapt resource value: 0x7f040015
			public const int optMinTemp = 2130968597;
			
			// aapt resource value: 0x7f04001b
			public const int optPressure = 2130968603;
			
			// aapt resource value: 0x7f040014
			public const int optionalGrid = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int optionalTxtGrid = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int resCoordinates = 2130968606;
			
			// aapt resource value: 0x7f04001a
			public const int resHumidity = 2130968602;
			
			// aapt resource value: 0x7f040018
			public const int resMaxTemp = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int resMinTemp = 2130968598;
			
			// aapt resource value: 0x7f04001c
			public const int resPressure = 2130968604;
			
			// aapt resource value: 0x7f040004
			public const int searchBtn = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int something = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int temperatureRes = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int temperatureTxt = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int txtCity = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int txtDefault = 2130968584;
			
			// aapt resource value: 0x7f040013
			public const int txtOptional = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int windRes = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int windTxt = 2130968592;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
